[package]
name = "cacabake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2.24" # for simpler arguments handling
crossterm = "0.29.0" # for manipulating the terminal
evalexpr = "13.1.0" # for evaluating string math expressions (again framerate)
tokio = { version = "1.51.0", features = ["full"] }
indicatif = "0.18.4" # for the progress bar UwU